name: 'automated_testing_framework_plugin_github'
description: 'Library to use provide github support for test hosting for the Automated Testing Framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_github'
version: '2.0.1+5'

environment: 
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  automated_testing_framework_models: '^2.0.10+2'
  convert: '^3.1.1'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.2.0+6'
  github: '^9.10.1'
  json_class: '^2.1.5+2'
  logging: '^1.1.1'
  pointycastle: '^3.6.2'
  static_translations: '^2.1.2+5'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
