name: 'automated_testing_framework_plugin_github'
description: 'Library to use provide github support for test hosting for the Automated Testing Framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_github'
version: '2.0.0+9'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework_models: '^2.0.9+6'
  convert: '^3.0.2'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+11'
  github: '^9.4.0'
  json_class: '^2.1.2+8'
  logging: '^1.0.2'
  pointycastle: '^3.6.1'
  static_translations: '^2.1.1+8'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
