name: 'automated_testing_framework_plugin_github'
description: 'Library to use provide github support for test hosting for the Automated Testing Framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_github'
version: '2.0.0+4'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework_models: '^2.0.9+2'
  convert: '^3.0.2'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+5'
  github: '^9.2.0'
  json_class: '^2.1.2+5'
  logging: '^1.0.2'
  pointycastle: '^3.6.0'
  static_translations: '^2.1.1+3'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true
